repos:
    - repo: https://github.com/ambv/black
      rev: 22.8.0
      hooks:
          - id: black
            args: [ --fast ]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            language_version: python3
    - repo: https://github.com/pycqa/flake8
      rev: '3.7.7'
      hooks:
          - id: flake8
            language_version: python3
    # I forked it because 0.971 is the last mypy that worked with 3.6, but the pre-commit hook install only ran under 3.7...
    -   repo: https://github.com/LiamClarkeNZ/precommit-mypy-fork
        rev: 'v0.971-fixed'
        hooks:
            - id: mypy
              types: [ python ]
              exclude_types: [ pyi ]
              language: python